### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ggomma** [kne6379/stephenShop#6]
# feedback

## 총평

- readme.md 를 잘 작성해주셨습니다.
- 불팔요한 코드가 부분적으로 보입니다.
- 코드에 대한 이해도가 어느정도 많이 생긴 것으로 보입니다.
- 조금 더 차분하게 '어떻게 코드를 더 줄일 수 있을까?', '어떤 예외 케이스가 있을까?'에 대한 고민을 해보는 것이 좋습니다.
- 지금까지도 그래왔지만 앞으로도 잘 하실거라 믿습니다. 화이팅

## 필요 구현 사항

1. 필수
- 상품 생성 API
  - [x] **상품명, 상품 설명, 담당자, 비밀번호**를 Request body(`req.body`)로 전달 받습니다.
  - [x] 상품은 두 가지 상태, **판매 중(`FOR_SALE`)및 판매 완료(`SOLD_OUT`)** 를 가질 수 있습니다.
  - [x] 상품 등록 시 기본 상태는 **판매 중(`FOR_SALE`)** 입니다.
  - [x] **생성 일시, 수정 일시**를 자동으로 생성합니다.
- 상품 목록 조회 API
  - [x] **상품 ID, 상품명, 상품 설명, 담당자, 상품 상태, 생성 일시, 수정 일시** 를 조회합니다.
  - [x] **비밀번호**를 포함하면 안됩니다.
  - [x] 상품 목록은 **생성 일시**를 기준으로 **내림차순(최신순)** 정렬합니다.
- 상품 상세 조회 API
  - [x] **상품 ID**를 Path Parameter(`req.params`)로 전달 받습니다.
  - [x] **상품 ID, 상품명, 상품 설명, 담당자, 상품 상태, 생성 일시, 수정 일시** 를 조회합니다.
  - [x] **비밀번호**를 포함하면 안됩니다.
- 상품 수정 API
  - [x] **상품 ID**를 Path Parameter(`req.params`)로 전달 받습니다.
  - [x] **상품명, 상품 설명, 담당자, 상품 상태, 비밀번호**를 Request body(`req.body`)로 전달 받습니다.
  - [ ] **수정할 상품과 비밀번호 일치 여부를 확인**한 후, 동일할 때만 상품이 **수정**되어야 합니다. 일치하지 않을 경우, **“비밀번호가 일치하지 않습니다.”** 메세지를 반환합니다.
- 상품 삭제
  - [x] **상품 ID**를 Path Parameter(`req.params`)로 전달 받습니다.
  - [x] **비밀번호**를 Request body(`req.body`)로 전달 받습니다.
  - [x] **삭제할 상품과 비밀번호 일치 여부를 확인**한 후, 동일할 때만 글이 **삭제**되어야 합니다. 일치하지 않을 경우, **“비밀번호가 일치하지 않습니다.”** 메세지를 반환합니다.

2. 선택
- 에러 처리 (에러 처리 미들웨어)
  - [x] **상품 상세 조회, 수정, 삭제 시** **상품이 없는 경우**에는 “**상품이 존재하지 않습니다.**” 메세지를 반환합니다. **상품 목록 조회 시** **상품이 없는 경우**에는 **빈 배열(`[]`)을 반환**합니다.
  - [x] **상품 생성 시** 입력 받은 상품명이 **기존에 등록 된 상품명과 동일한 경우**에는 **“이미 등록 된 상품입니다.”** 메세지를 반환합니다.
  - [x] **그 밖의 에러가 발생했을 때**에는 **“예상치 못한 에러가 발생했습니다. 관리자에게 문의해 주세요.”** 메세지를 반환합니다.
- 유효성 검증 (Joi)
  - [x] **상품 생성 시 정보가 빠진 경우**, **“OOO을(를) 입력해 주세요.”** 메시지를 반환합니다. 예) “상품명을 입력해 주세요”, “담당자를 입력해 주세요.” 등…
  - [ ] **상품 수정, 삭제 시 비밀번호가 없는 경우**, **“비밀번호를 입력해 주세요.”** 메세지를 반환합니다.
  - [x] **상품 수정 시** 상품 상태에 `FOR_SALE`, `SOLD_OUT` 이 외의 다른 값이 입력된 경우, **“상품 상태는 [FOR_SALE,SOLD_OUT] 중 하나여야 합니다.”** 메세지를 반환합니다.

### 실행 스크립트
서버를 실행하는 스크립트를 package.json에 넣어주는 것이 사용하기에 좋습니다.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/package.json#L7-L9

### 중복 코드 삭제
`app.js`에서 이미 `dotenv` 설정을 진행하였으므로 아래 코드는 불필요한 코드입니다.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/schemas/index.js#L1-L5

### 주석
TODO로 표시하는 주석 중 완료된 것들은 삭제해주는 것이 좋습니다.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/schemas/index.js#L4

### 코드는 기능별로 나누는 것이 좋습니다.
joi에 관련된 내용은 별도 파일로 작성하는 것이 가독성에 좋습니다.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/routes/goods.router.js#L7-L30

### joi 사용법 개선
아래 코드에서 `createdAt`, `updatedAt`, `GoodsStatus`는 존재하지 않습니다. joi 문서를 다시 읽어보시면 도움이 될거에요.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/routes/goods.router.js#L36-L44

### 데이터 존재 여부 확인
데이터 존재 여부를 확인하기 위해서는 다음의 코드를 사용하는 것이 좋습니다.

```javascript
if (!goods) { ... }
```

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/routes/goods.router.js#L73

### optional 데이터
상품 데이터를 업데이트할 때에는 굳이 모든 데이터를 받을 필요가 없습니다. 때문에 joi schema를 새로 선언해주고 아래 코드들에 대한 수정이 필요합니다.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/routes/goods.router.js#L107
https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/routes/goods.router.js#L121-L126

### password 비교
아래 코드에서 `passwordCheck`과 `password`를 나눠서 사용할 필요는 없어보입니다.

https://github.com/kne6379/stephenShop/blob/d220d74b6922f340532965ca1e1506abe7513827/src/routes/goods.router.js#L118-L120

**Comment by kne6379** [comment]
피드백 감사합니다 !! 반영하도록 하겠습니다.
